- name: Configure Nagios slave
  hosts: slaves
  sudo: true
  tasks:
    - name: install packages
      yum: name={{ item }} state=present
      with_items:
        - nagios
        - nagios-plugins-all
        - nrpe
        
    - name: copy client nrpe config
      template: src=../templates/nrpe.cfg.j2 dest=/etc/nagios/nrpe.cfg owner=root mode=0644
      
    - name: Open port 5666
      command: /sbin/iptables -I INPUT 1 -p tcp --dport 5666 -j ACCEPT -m comment --comment "NRPE"
      
    - name: start nrpe
      service: name=nrpe state=started enabled=yes